### ISSUE TITLE
Always show total clocked time (also if not currently clocked-in)

### ISSUE THREAD

**Issue by stefan2904** [mallt/org-clock-today-mode#3]
Thanks for the mode!

Is there a way to display the total clocked time of the current day also while no task is clocked?

My use case is basically to see "how much time did I already clock today/how much time do I still need to clock".
It seems this is currently not possible, is this correcT?

Thanks!

**Comment by mallt** [comment]
Hi @stefan2904, thank you for your message! 

I've added the option `org-clock-today-show-mode-line-when-clock-is-inactive` to always show the mode line. If no clock is active `(inact)` will be shown next to the total time. 

The new option should become available today in melpa.

**Comment by stefan2904** [comment]
Hi Tijs, it works! Thanks a lot!
